forge "https://forgeapi.puppetlabs.com"

# Module for access to NSIDC Enterprise storage
mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => 'puppet7'

# Module for creating NSIDC Jenkins servers
mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => 'work-with-java'

# Module to install Solr
mod "nsidc/nsidc_solr",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-solr.git",
  :ref  => 'srch-120'

# Module for installing rbenv (and by extension, ruby)
mod 'jdowning-rbenv', "2.5.0"